version: '3.8'

services:

  dashboard:
    container_name: central-server-dashboard
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on: 
      - broker
    volumes: 
      - ./central-server:/central-server/
    ports: 
      - "3000:3000"

  broker:
    container_name: local-emqx-broker
    image: emqx/emqx
    environment:
      - EMQX_HOST=127.0.0.1
      - EMQX_NAME=local-emqx-broker
    ports: 
      - "8083:8083"
